spec_file_name: aggregate_zone.csv

# values available to expressions in aggregate_zone_processor
CONSTANTS:
  #auto ownership variables
  ANNUAL_COST_PER_VEHICLE: 6611
  AVERAGE_AUTOS_IN_3PLUS: 3.5
  #utilities per minute (Kate IVT coefficients, use work for sch as well)
  UPM_HBC: 0.0346
  UPM_HBO: 0.0315
  UPM_HBR: 0.0315
  UPM_HBS: 0.0315
  UPM_HBW: 0.0414
  UPM_NHBNW: 0.0278
  UPM_NHBW: 0.0452
  UPM_SCH: 0.0414
  #value-of-time ($/hour; currently all equal, USDOT)
  VOT_HBC: 14.66
  VOT_HBO: 14.66
  VOT_HBR: 14.66
  VOT_HBS: 14.66
  VOT_HBW: 14.66
  VOT_NHBNW: 14.66
  VOT_NHBW: 14.66
  VOT_SCH: 14.66
