# file name for hhs table csv data input file (expect versions in build and base data subdirs)
hh_file_name: mf.cval.csv

# file name for external cocs table csv data input file (expect versions in build and base data subdirs)
ext_cocs_file_name: cocs.csv

# file name for csv file in data dir with list of zone districts (which district each zone is in)
district_file_name: zone_districts.csv


# file name for zones table csv data input files (expect versions in build and base data subdirs)
# data will be combined into a single table with columns names prefixed with 'base_' or 'build_'
# (e.g.) if ma.hbcdcls.csv has a column 'hbcdcls' you will have 'base_hbcdcls' and 'build_hbcdcls'
aggregate_zone_file_names:
  - ma.hbcdcls.csv
  - ma.hbohdcls.csv
  - ma.hbomdcls.csv
  - ma.hboldcls.csv
  - ma.hbrhdcls.csv
  - ma.hbrldcls.csv
  - ma.hbrmdcls.csv
  - ma.hbsldcls.csv
  - ma.hbsmdcls.csv
  - ma.hbshdcls.csv
  - ma.hbwhdcls.csv
  - ma.hbwldcls.csv
  - ma.hbwmdcls.csv
  - ma.nhbnwdcls.csv
  - ma.nhbwdcls.csv
  - ma.schdcls.csv
  - mf.cval.csv
  - ma.collpr.csv
  - ma.hboprh.csv
  - ma.hboprl.csv
  - ma.hboprm.csv
  - ma.hbrprh.csv
  - ma.hbrprl.csv
  - ma.hbrprm.csv
  - ma.hbsprh.csv
  - ma.hbsprl.csv
  - ma.hbsprm.csv
  - ma.hbwprh.csv
  - ma.hbwprl.csv
  - ma.hbwprm.csv
  - ma.nhnwpr.csv
  - ma.nhwpr.csv
  - ma.schpr.csv
  - parking_cost.csv

# file name for csv file in data dir with a column mapping zone_id to offset
# zone_ids file must have a column with a name in zone_aliases containing zone_ids
# this positional mapping applies to all zone files and skims
# assumes default (1-based) zone_ids if this setting is omitted
zone_ids: zone_districts.csv

# list of column names that may be synonyms for zone column names in the above files
# (in case different files from different sources have different zone id columns names)
#zone_aliases:
#  - zone
#  - TAZID
#  - TAZ
