provenance: example_4step.configs

dump: True

trace_od: [5, 11]


coc_columns:
  - coc_poverty
  - coc_age

# values available to all processors
globals:
  SAMPLE_GLOBAL_CONSTANT: 0.75

# file name for cvals table csv data input file (expect versions in build and base data subdirs)
cval_file_name: mf.cval.csv

# values available to expressions in aggregate_demographics_processor
locals_aggregate_demographics:
  SAMPLE_CONSTANT: 42

# file name for zones table csv data input files (expect versions in build and base data subdirs)
# data will be combined into a single table with columns names prefixed with 'base_' or 'build_'
# (e.g.) if ma.hbcdcls.csv has a column 'hbcdcls' you will have 'base_hbcdcls' and 'build_hbcdcls'
aggregate_zone_file_names:
  - ma.hbcdcls.csv
  - ma.hbohdcls.csv
  - ma.hbomdcls.csv
  - ma.hbrhdcls.csv
  - ma.hbrldcls.csv
  - ma.hbrmdcls.csv
  - ma.hbsldcls.csv
  - ma.hbsmdcls.csv
  - ma.hbwhdcls.csv
  - ma.hbwldcls.csv
  - ma.nhbnwdcls.csv
  - ma.nhbwdcls.csv
  - ma.schdcls.csv

# values available to expressions in aggregate_zone_processor
locals_aggregate_zone:
  SAMPLE_CONSTANT: 2000
