
link_daily_file_name: link_daily.csv

link_daily_table_column_map:
  distance: distance
  dircode: dircode
  time: time
  congtime: congested_time
  area_type: area_type
  facl_type: facility_type_code
  num_lanes: num_lanes
  capacity: capacity
  twoway: two_way
  vol_total: total_volume
  trk_vol: truck_volume


CONSTANTS:
  # accident costs
  # Crash rates per vehicle-mile
  CRASH_RATE_PDO: 0.0001
  CRASH_RATE_INJURY: 0.00001
  CRASH_RATE_FATAL: 0.000001
  # Crash costs in Dollars
  CRASH_COST_PDO: 1522
  CRASH_COST_INJURY: 441800
  CRASH_COST_FATAL: 9400000

# specify column name to enable zone tracing for both the o and the d zone
# (if not specified, just trace first link)
od_column: zone
