scenario_label: sample

#output_store: store.h5

households: households.csv
households_column_map:
  hhno: hh_id
  hhincome: hh_income
  hhsize: hh_size

persons: persons.csv
persons_column_map:
  pno: person_idx
  hhno: hh_id
  pptyp: person_type
  pgend: person_gender
  pagey: person_age

bca_base_trips: basetrips.csv
bca_base_trips_alt: basetrips_alt.csv

bca_build_trips: buildtrips.csv
bca_build_trips_alt: buildtrips_alt.csv

trips_column_map:
  pno: person_idx
  hhno: hh_id
  tour: tour_idx
  half: half_tour_idx
  tseg: half_tour_seg_idx
  pdpurp: tour_purpose
  mode: trip_mode
  autotime: auto_time
  transittime: transit_time
  biketime: bike_time
  walktime: walk_time
  travcost: travel_cost

trips_alt_column_map:
  pno: person_idx
  hhno: hh_id
  tour: tour_idx
  half: half_tour_idx
  tseg: half_tour_seg_idx
  autotime: alt_auto_time
  transittime: alt_transit_time
  biketime: alt_bike_time
  walktime: alt_walk_time
  travcost: alt_travel_cost

person_type_map:
    1: full
    2: part
    3: retired
    4: nonwork
    5: university
    6: highschool
    7: school
    8: preschool

gender_map:
    1: male
    2: female


trip_mode_map:
    1: walk      # walk
    2: walk      # bike
    3: auto      # drive-alone
    4: auto      # shared-ride-2
    5: auto      # shared-ride-3+
    6: transit   # walk-transit
    7: transit   # drive-transit
    8: transit   # school-bus

tour_purpose_map:
    0: noncommute   # home
    1: commute   # work
    2: commute   # school
    3: noncommute   # escort
    4: noncommute   # chore
    5: noncommute   # shop
    6: noncommute   # meal
    7: noncommute   # social

tour_purpose_vot_map:
    0: 5.00     # home
    1: 11.03    # work
    2: 11.03    # school
    3: 5.00     # escort
    4: 5.00     # chore
    5: 5.00     # shop
    6: 5.00     # meal
    7: 5.00     # social

ovt_weight: 2.2
