dump: True
#dump_aggregate_trips: True
#dump_auto_ownership: True
#dump_demographics: True
#dump_link: True
#dump_link_daily: True
#dump_physical_activity: True

# trace household id; comment out for no trace
trace_hh_id: 60

chunk_size: 5

scenario_year: sample

# local values available to all processors
globals:
  DISCOUNT_RATE: 0.75
  ANNUALIZATION_FACTOR: 365

locals_demographics:
  POVERTY_1: 11770
  POVERTY_2: 15930
  POVERTY_N: 4160

locals_auto_ownership:
  ANNUAL_COST_PER_VEHICLE: 2000

locals_physical_activity:
  WALK_FACTOR_AGE_UNDER_20: 0
  WALK_FACTOR_AGE_20_TO_74: 0.11
  WALK_FACTOR_AGE_75_PLUS: 0
  WALK_DIVISOR_MINUTES_PER_DAY: 24
  WALK_MAX_RISK_REDUCTION: 0.3
  BIKE_FACTOR_AGE_UNDER_20: 0
  BIKE_FACTOR_AGE_20_TO_64: 0.1
  BIKE_FACTOR_AGE_65_PLUS: 0
  BIKE_DIVISOR_MINUTES_PER_DAY: 14.3
  BIKE_MAX_RISK_REDUCTION: 0.45
  TOTAL_MAX_RISK_REDUCTION: 0.45
  VALUE_OF_MORTALITY_RISK_PER_YEAR: 100000


locals_person_trips:
  # map trips table tour_purpose to work/notwork boolean
  TOUR_PURPOSE_WORK_MAP:
    0: 0   # home
    1: 1   # work
    2: 0   # school
    3: 0   # escort
    4: 0   # chore
    5: 0   # shop
    6: 0   # meal
    7: 0   # social
  # work/nonwork in-vehicle-time value of time
  WORK_IVT_VOT_MAP:
      0: 6.0     # nonwork
      1: 10.0    # work
  # work/nonwork walk value of time
  WORK_WALK_VOT_MAP:
      0: 9.0     # nonwork
      1: 15.0    # work
  # work/nonwork wait value of time
  WORK_WAIT_VOT_MAP:
      0: 9.0     # nonwork
      1: 15.0    # work
  TOLL_INCLUSION_FACTOR: 1
  FUEL_INCLUSION_FACTOR: 1
  PARK_INCLUSION_FACTOR: 1
  FARE_INCLUSION_FACTOR: 1

locals_link:
  # unreliability costs - inputs
  RELIABILITY_RATIO: 0.5
  VALUE_OF_RELIABILITY_AUTO: 10.00
  VALUE_OF_RELIABILITY_TRUCK: 40.00
  # unreliability costs - constants
  TIME_RATIO_FACTOR: 1.0274
  TIME_RATIO_POWER: 1.2204
  TIME_RATIO_UPPER_LIMIT: 3
  TTI50_POWER: 0.8601
  TTI80_LOG_MULTIPLIER: 2.1406
  # operating costs
  OPERATING_COST_PER_MILE_AUTO: 0.20
  OPERATING_COST_PER_MILE_TRUCK: 0.80

locals_link_daily:
  # accident costs
  # Crash rates per vehicle-mile
  CRASH_RATE_PDO: 0.0001
  CRASH_RATE_INJURY: 0.00001
  CRASH_RATE_FATAL: 0.000001
  # Crash costs in Dollars
  CRASH_COST_PDO: 2500
  CRASH_COST_INJURY: 25000
  CRASH_COST_FATAL: 100000

locals_aggregate_trips:
  AOC_COST_COUNTING_FACTOR: 1.0
  TOLL_COST_COUNTING_FACTOR: 1.0


### table definitions

base_households: base_households.csv
base_households_column_map:
  hhno: hh_id
  hhincome: hh_income
  hhsize: hh_size
  hhexpfac: hh_expansion_factor
  hhvehs: base_vehicles

build_households: build_households.csv
build_households_column_map:
  hhno: hh_id
  hhvehs: build_vehicles

persons: persons.csv
persons_column_map:
  pno: person_idx
  hhno: hh_id
  pptyp: person_type
  pgend: person_gender
  pagey: person_age

basetrips: basetrips_normal.csv
basetrips_column_map:
  pno: person_idx
  hhno: hh_id
  tour: tour_idx
  half: half_tour_idx
  tseg: half_tour_seg_idx
  pdpurp: tour_purpose
  mode: trip_mode
  autotime: base_auto_time
  transittime: base_transit_time
  transitwait: base_transit_wait
  transitwalk: base_transit_walk
  biketime: base_bike_time
  walktime: base_walk_time
  tollcost: base_toll_cost
  fuelcost: base_fuel_cost
  parkcost: base_park_cost
  farecost: base_fare_cost


basetrips_buildlos: basetrips_buildlos.csv
basetrips_buildlos_column_map:
  pno: person_idx
  hhno: hh_id
  tour: tour_idx
  half: half_tour_idx
  tseg: half_tour_seg_idx
  autotime: build_auto_time
  transittime: build_transit_time
  transitwait: build_transit_wait
  transitwalk: build_transit_walk
  biketime: build_bike_time
  walktime: build_walk_time
  tollcost: build_toll_cost
  fuelcost: build_fuel_cost
  parkcost: build_park_cost
  farecost: build_fare_cost

buildtrips: buildtrips_normal.csv
buildtrips_column_map:
  pno: person_idx
  hhno: hh_id
  tour: tour_idx
  half: half_tour_idx
  tseg: half_tour_seg_idx
  pdpurp: tour_purpose
  mode: trip_mode
  autotime: build_auto_time
  transittime: build_transit_time
  transitwait: build_transit_wait
  transitwalk: build_transit_walk
  biketime: build_bike_time
  walktime: build_walk_time
  tollcost: build_toll_cost
  fuelcost: build_fuel_cost
  parkcost: build_park_cost
  farecost: build_fare_cost

buildtrips_baselos: buildtrips_baselos.csv
buildtrips_baselos_column_map:
  pno: person_idx
  hhno: hh_id
  tour: tour_idx
  half: half_tour_idx
  tseg: half_tour_seg_idx
  autotime: base_auto_time
  transittime: base_transit_time
  transitwait: base_transit_wait
  transitwalk: base_transit_walk
  biketime: base_bike_time
  walktime: base_walk_time
  tollcost: base_toll_cost
  fuelcost: base_fuel_cost
  parkcost: base_park_cost
  farecost: base_fare_cost

# expected column headers in aggregate_data_manifest.csv
# this is as much to document the expected columns as anything
# but it does allow you to use different column headers
aggregate_data_manifest_column_map:
  description: description
  trip_file_name: trip_file_name
  trip_table_name: trip_table_name
  ivt_file_name: ivt_file_name
  ivt_table_name: ivt_table_name
  dollars_per_hour: vot
  aoc_file_name: aoc_file_name
  aoc_table_name: aoc_table_name
  aoc_dollars_per_unit: aoc_units
  toll_file_name: toll_file_name
  toll_table_name: toll_table_name
  toll_dollars_per_unit: toll_units

link_data_manifest_column_map:
  description: description
  link_file_name: link_file_name

link_table_column_map:
  distance: distance
  dircode: dircode
  time: time
  congtime: congested_time
  area_type: area_type
  facl_type: facility_type_code
  num_lanes: num_lanes
  capacity: capacity
  twoway: two_way
  vol_total: total_volume
  trk_vol: truck_volume

link_daily_file_name: link_daily.csv
