
#store: store.h5
#output_store: store.h5

bca_households: households.csv
bca_households_column_map:
  hhno: hh_id
  hhincome: hh_income
  hhtaz: hh_taz

bca_persons: persons.csv
bca_persons_column_map:
  pno: person_idx
  hhno: hh_id
  pptype: person_type
  pgend: person_gender
  pagey: person_age

person_type_map:
    1: full
    2: part
    3: university
    4: nonwork
    5: retired
    6: driving
    7: school
    8: preschool
